### ISSUE TITLE
Travel Time in Agent File

### ISSUE THREAD

**Issue by zanmdi** [jdlph/Path4GMNS#45] opened 2023-11-14 10:45 UTC
Hello, how is the travel time in the agent.csv file calculated? When I compare the travel time between zones in this file with the EU travel time using the link_performance.csv file they are not consistent.

**Comment by jdlph** [comment] 2023-12-08 00:45
Travel time in agent.csv is path travel time, which is a summation of the link travel time over links along each path (column). Calculation details can be found in _update_column_attributes() under colgen.py.

If you have found inconsistency, please provide the following things so that we can conduct the proper investigation.

1. The details over the claimed inconsistency.
2. The input data set.
3. Runtime information which includes OS, the version of Path4GMNS, the function you called (leading to the claimed consistency).

**Comment by jdlph** [comment] 2024-04-27 23:05
The issue is closed as no further information was received to support the claim.

**Closed by jdlph** 2024-04-27 23:05 UTC
Labels: help wanted
